// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Uuid = require("bs-guid/src/Uuid.js");

var uuidv4 = Uuid.V4[/* uuidv4 */0];

function newItem(text) {
  return /* record */[
          /* id */uuidv4(/* () */0),
          /* title */text,
          /* completed */false
        ];
}

exports.uuidv4 = uuidv4;
exports.newItem = newItem;
/* Uuid Not a pure module */
