// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function Todo(Props) {
  var item = Props.item;
  var label = Props.label;
  var onToggle = Props.onToggle;
  var onDelete = Props.onDelete;
  var match = React.useState((function () {
          return false;
        }));
  var setEditing = match[1];
  var match$1 = React.useState((function () {
          return label;
        }));
  var onChange = match$1[1];
  var value = match$1[0];
  var onCancel = function (_evt) {
    return Curry._1(setEditing, (function (param) {
                  return false;
                }));
  };
  var onFocus = function ($$event) {
    return $$event.target.select();
  };
  var tmp;
  if (match[0]) {
    tmp = React.createElement("form", {
          onBlur: onCancel,
          onSubmit: (function (evt) {
              evt.preventDefault();
              return Curry._1(setEditing, (function (param) {
                            return false;
                          }));
            })
        }, React.createElement("input", {
              value: value,
              onFocus: onFocus,
              onBlur: onCancel,
              onChange: (function (evt) {
                  return Curry._1(onChange, evt.target.value);
                })
            }));
  } else {
    var match$2 = item.completed;
    tmp = React.createElement(React.Fragment, undefined, React.createElement("label", {
              className: match$2 ? "checkbox is-checked" : "checkbox"
            }, React.createElement("input", {
                  defaultChecked: item.completed,
                  type: "checkbox",
                  onClick: (function (_evt) {
                      return Curry._1(onToggle, /* () */0);
                    })
                }), " ", value), React.createElement("span", {
              className: "icon is-pulled-right",
              onClick: (function (_evt) {
                  return Curry._1(onDelete, /* () */0);
                })
            }, React.createElement("i", {
                  className: "fas fa-times"
                })), React.createElement("span", {
              className: "icon is-pulled-right",
              onClick: (function (_evt) {
                  return Curry._1(setEditing, (function (param) {
                                return true;
                              }));
                })
            }, React.createElement("i", {
                  className: "fas fa-pencil-alt"
                })));
  }
  return React.createElement("li", {
              className: "list-item"
            }, tmp);
}

var make = Todo;

exports.str = str;
exports.make = make;
/* react Not a pure module */
